server:
  error:
    include-message: always
    include-stacktrace: always
    whitelabel: 
      enabled: true      
    include-exception: true
    include-binding-errors: always  


spring:
  application:
    name: data-rest
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration    
  servlet:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB
  security:
    oauth2:
#      client:
#        registration:
#          google:
#            client-id: @client.id@
#            client-secret: @client.secret@
#            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  cloud:
    gcp:
      datastore:
        namespace: spring-demo
    project-id: @app.deploy.projectId@
#    logging:
#      enabled: true
  data:
    rest:
      base-path: /apis
#      returnBodyOnUpdate: true
#      returnBodyOnCreate: true
      
#  main:
#    allow-circular-references: true
  profile:
    active: test_user    
  mvc:
    problemdetails:
      enabled: true      
 #     throw-exception-if-no-handler-found: true
 
springdoc:
  api-docs:
    path: /apis-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true    
    
data-rest:
  admin:
    emails: @admin.emails@
  storage:
    bucketName: @storage.bucketName@
    
logging:
  level:
    root: OFF
#    org:
#      springframework:
#        security: TRACE
#        data:
#          rest: OFF  
#        web: TRACE                
#      apache:
#        tomcat: OFF
#        catalina: OFF
#      springdoc: OFF
#    io:
#      swagger: OFF
      


          
