spring:
  security:
    oauth2:
#      client:
#        registration:
#          google:
#            client-id: @client.id@
#            client-secret: @client.secret@
#            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

logging:
  level:
    org:
      springframework:
        security: DEBUG
