app:
  rick-and-Morty-api-url: https://rickandmortyapi.com
      
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect    
  h2:
    console:
      enabled: true
      path: /h2-console      
  data:
    rest:
      base-path: /apis
      
springdoc:
  api-docs:
    path: /apis-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true          

logging:
  level:
    com.example.demo: INFO
    org.springframework.web.reactive.function.client: OFF
