version: "3.8"

services:

  vt-servlet-service:
    depends_on:
      - postgres-service
    image: "ghcr.io/consolidando/vt-tomcat:6"
    container_name: "vt-tomcat-with-vt-limited"
    ports:
      - 8080:8080
      - 8001:8001 # debug
      - 5000:5000 # jmxremote
    environment:
      - BP_JVM_VERSION=21
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001      
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/character
      - SPRING_PROFILES_ACTIVE=servlet
      - BPL_JMX_ENABLED=true
      - BPL_JMX_PORT=5000    
      - JAVA_TOOL_OPTIONS= -XX:ActiveProcessorCount=3 
      # - JAVA_TOOL_OPTIONS= -Dserver.tomcat.accesslog.enabled=true
      # - JAVA_TOOL_OPTIONS= -Dlogging.level.org.apache.tomcat=INFO -Dlogging.level.org.apache.catalina=INFO
      # - JAVA_TOOL_OPTIONS= -Dlogging.level.root=INFO
    command: ["--app.episode=10"]
    deploy:
      resources:
        limits:
          cpus: '3'

  postgres-service:
    image: "postgres:16.2"
    container_name: "postgres"
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/data/db      
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=character
    deploy:
      resources:
        limits:
          cpus: '2'

volumes:
  postgres_data:
  pgadmin_data: