version: "3.8"

services:

  vt-netty-service:
    depends_on:
      - postgres-service
    image: "ghcr.io/consolidando/vt-netty:5"
    container_name: "vt-netty"
    ports:
      - 8080:8080
      - 8001:8001
      - 5000:5000
    environment:
      - BP_JVM_VERSION=21
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001      
      - SPRING_DATASOURCE_URL=r2dbc:postgresql://postgres-service:5432/character
      - SPRING_PROFILES_ACTIVE=flux
      - BPL_JMX_ENABLED=true
      - BPL_JMX_PORT=5000    
      - JAVA_TOOL_OPTIONS= -XX:ActiveProcessorCount=3 # -Dlogging.level.root=INFO
    command: ["--app.episode=10"]
    deploy:
      resources:
        limits:
          cpus: '3'

  postgres-service:
    image: "postgres:16.2"
    container_name: "postgres"
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/data/db      
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=character
    deploy:
      resources:
        limits:
          cpus: '2'

volumes:
  postgres_data:
  pgadmin_data: