spring:
  datasource:
    r2dbc:
      url: r2dbc:h2:mem:///testdb
      driver: h2
      username: sa
      password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  r2dbc:
    url: r2dbc:h2:mem:///testdb
    pool:
      enabled: true
      initial-size: 1
      max-size: 10
    initialization-mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    r2dbc:
      repositories:
        enabled: true      

