app:
  rick-and-Morty-api-url: https://rickandmortyapi.com  
  useSaveAllInRepository: true
  episode: 0
      
spring:
  application:
    name: Virtual Threads
  profiles: 
    active: @spring.profiles.active@



logging:
  level: 
    root: OFF
#    io.netty: OFF
#    reactor: OFF
#    org.postgresql: TRACE
#    io.r2dbc.postgresql: TRACE
#    io.r2dbc.postgresql.QUERY: DEBUG 
#    io.r2dbc.postgresql.PARAM: DEBUG
#    io.r2dbc.postgresql.client: TRACE
    com.elmoli.consolidando.vt: INFO
#    io.r2dbc: DEBUG
#    org.springframework.data: OFF
#    org.springframework.data.r2dbc: DEBUG
#    org.springframework.web.reactive.function.client: OFF
#    org.hibernate: DEBUG
