# ------------------
app:
  tomcat:  
    virtual-threads:
      concurrency-limit: 200
  episode-service: graphql  # simple, executors, graphql  

# ------------------
#server: 
#  tomcat:
#    threads: 
#      max: 100
#    mbeanregistry:
#      enabled: true

# ------------------
spring:  
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration    
  threads:
    virtual:
      enabled: true
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/character
#    hikari:
#      connection-timeout: 4000
#      maximum-pool-size: 5
  sql:
    init:
      mode: always
#  task:
#    execution:
#      simple:
#        concurrency-limit: 200
      
  data:
    r2dbc:
      repositories:
        enabled: false  
      
#  jpa:
#    hibernate:
#      ddl-auto: create

      
     
