spring:  
  threads:
    virtual:
      enabled: true
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/character
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  sql:
    init:
      mode: always
      
#  jpa:
#    hibernate:
#      ddl-auto: create

      
#springdoc:
#  api-docs:
#    path: /apis-docs
#  swagger-ui:
#    path: /swagger-ui.html
#    enabled: true          
